/**
 * ERRORS
 * 
 * 
 */

try {
    const numero;
} catch (error) {
    console.log("Erro : " + error.getMessage());
}